# Generated by Django 3.2.9 on 2021-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.TextField(db_column='id', primary_key=True, serialize=False)),
                ('isbn', models.TextField(blank=True, db_column='ISBN', null=True)),
                ('userid', models.TextField(blank=True, db_column='UserID', null=True)),
                ('bookrating', models.TextField(blank=True, db_column='BookRating', null=True)),
                ('booktitle', models.TextField(blank=True, db_column='BookTitle', null=True)),
                ('bookauthor', models.TextField(blank=True, db_column='BookAuthor', null=True)),
                ('yearofpublication', models.TextField(blank=True, db_column='YearOfPublication', null=True)),
                ('publisher', models.TextField(blank=True, db_column='Publisher', null=True)),
                ('imageurls', models.TextField(blank=True, db_column='ImageURLS', null=True)),
                ('imageurlm', models.TextField(blank=True, db_column='ImageURLM', null=True)),
                ('imageurll', models.TextField(blank=True, db_column='ImageURLL', null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
    ]
