# Generated by Django 3.2.9 on 2021-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField(blank=True, db_column='ISBN', null=True)),
                ('book_title', models.TextField(blank=True, db_column='Book-Title', null=True)),
                ('book_author', models.TextField(blank=True, db_column='Book-Author', null=True)),
                ('year_of_publication', models.TextField(blank=True, db_column='Year-Of-Publication', null=True)),
                ('publisher', models.TextField(blank=True, db_column='Publisher', null=True)),
                ('image_url_s', models.TextField(blank=True, db_column='Image-URL-S', null=True)),
                ('image_url_m', models.TextField(blank=True, db_column='Image-URL-M', null=True)),
                ('image_url_l', models.TextField(blank=True, db_column='Image-URL-L', null=True)),
                ('user_id', models.TextField(blank=True, db_column='User-ID', null=True)),
                ('book_rating', models.TextField(blank=True, db_column='Book-Rating', null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
    ]
