# Generated by Django 3.2.9 on 2021-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
